<<<<<<< HEAD
[build]
builder = "nixpacks"

[deploy]
start = "gunicorn perfume_store.wsgi:application --bind 0.0.0.0:$PORT"

=======
[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
startCommand = "npm run start"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
port = 3000

[env]
NODE_ENV = "production" 
>>>>>>> 23cbfa4 (Updated dependencies for Railway)
